# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ondra/projekty/ld34

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ondra/projekty/ld34

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ondra/projekty/ld34/CMakeFiles /home/ondra/projekty/ld34/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ondra/projekty/ld34/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named spacepilot

# Build rule for target.
spacepilot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spacepilot
.PHONY : spacepilot

# fast build rule for target.
spacepilot/fast:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/build
.PHONY : spacepilot/fast

Bullet.o: Bullet.cc.o

.PHONY : Bullet.o

# target to build an object file
Bullet.cc.o:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Bullet.cc.o
.PHONY : Bullet.cc.o

Bullet.i: Bullet.cc.i

.PHONY : Bullet.i

# target to preprocess a source file
Bullet.cc.i:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Bullet.cc.i
.PHONY : Bullet.cc.i

Bullet.s: Bullet.cc.s

.PHONY : Bullet.s

# target to generate assembly for a file
Bullet.cc.s:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Bullet.cc.s
.PHONY : Bullet.cc.s

Enemy.o: Enemy.cc.o

.PHONY : Enemy.o

# target to build an object file
Enemy.cc.o:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Enemy.cc.o
.PHONY : Enemy.cc.o

Enemy.i: Enemy.cc.i

.PHONY : Enemy.i

# target to preprocess a source file
Enemy.cc.i:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Enemy.cc.i
.PHONY : Enemy.cc.i

Enemy.s: Enemy.cc.s

.PHONY : Enemy.s

# target to generate assembly for a file
Enemy.cc.s:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Enemy.cc.s
.PHONY : Enemy.cc.s

Entity.o: Entity.cc.o

.PHONY : Entity.o

# target to build an object file
Entity.cc.o:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Entity.cc.o
.PHONY : Entity.cc.o

Entity.i: Entity.cc.i

.PHONY : Entity.i

# target to preprocess a source file
Entity.cc.i:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Entity.cc.i
.PHONY : Entity.cc.i

Entity.s: Entity.cc.s

.PHONY : Entity.s

# target to generate assembly for a file
Entity.cc.s:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Entity.cc.s
.PHONY : Entity.cc.s

Game.o: Game.cc.o

.PHONY : Game.o

# target to build an object file
Game.cc.o:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Game.cc.o
.PHONY : Game.cc.o

Game.i: Game.cc.i

.PHONY : Game.i

# target to preprocess a source file
Game.cc.i:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Game.cc.i
.PHONY : Game.cc.i

Game.s: Game.cc.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cc.s:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Game.cc.s
.PHONY : Game.cc.s

InputHandler.o: InputHandler.cc.o

.PHONY : InputHandler.o

# target to build an object file
InputHandler.cc.o:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/InputHandler.cc.o
.PHONY : InputHandler.cc.o

InputHandler.i: InputHandler.cc.i

.PHONY : InputHandler.i

# target to preprocess a source file
InputHandler.cc.i:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/InputHandler.cc.i
.PHONY : InputHandler.cc.i

InputHandler.s: InputHandler.cc.s

.PHONY : InputHandler.s

# target to generate assembly for a file
InputHandler.cc.s:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/InputHandler.cc.s
.PHONY : InputHandler.cc.s

Levels.o: Levels.cc.o

.PHONY : Levels.o

# target to build an object file
Levels.cc.o:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Levels.cc.o
.PHONY : Levels.cc.o

Levels.i: Levels.cc.i

.PHONY : Levels.i

# target to preprocess a source file
Levels.cc.i:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Levels.cc.i
.PHONY : Levels.cc.i

Levels.s: Levels.cc.s

.PHONY : Levels.s

# target to generate assembly for a file
Levels.cc.s:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Levels.cc.s
.PHONY : Levels.cc.s

Menu.o: Menu.cc.o

.PHONY : Menu.o

# target to build an object file
Menu.cc.o:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Menu.cc.o
.PHONY : Menu.cc.o

Menu.i: Menu.cc.i

.PHONY : Menu.i

# target to preprocess a source file
Menu.cc.i:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Menu.cc.i
.PHONY : Menu.cc.i

Menu.s: Menu.cc.s

.PHONY : Menu.s

# target to generate assembly for a file
Menu.cc.s:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Menu.cc.s
.PHONY : Menu.cc.s

Player.o: Player.cc.o

.PHONY : Player.o

# target to build an object file
Player.cc.o:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Player.cc.o
.PHONY : Player.cc.o

Player.i: Player.cc.i

.PHONY : Player.i

# target to preprocess a source file
Player.cc.i:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Player.cc.i
.PHONY : Player.cc.i

Player.s: Player.cc.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cc.s:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Player.cc.s
.PHONY : Player.cc.s

Renderer.o: Renderer.cc.o

.PHONY : Renderer.o

# target to build an object file
Renderer.cc.o:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Renderer.cc.o
.PHONY : Renderer.cc.o

Renderer.i: Renderer.cc.i

.PHONY : Renderer.i

# target to preprocess a source file
Renderer.cc.i:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Renderer.cc.i
.PHONY : Renderer.cc.i

Renderer.s: Renderer.cc.s

.PHONY : Renderer.s

# target to generate assembly for a file
Renderer.cc.s:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Renderer.cc.s
.PHONY : Renderer.cc.s

Star.o: Star.cc.o

.PHONY : Star.o

# target to build an object file
Star.cc.o:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Star.cc.o
.PHONY : Star.cc.o

Star.i: Star.cc.i

.PHONY : Star.i

# target to preprocess a source file
Star.cc.i:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Star.cc.i
.PHONY : Star.cc.i

Star.s: Star.cc.s

.PHONY : Star.s

# target to generate assembly for a file
Star.cc.s:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Star.cc.s
.PHONY : Star.cc.s

Texture.o: Texture.cc.o

.PHONY : Texture.o

# target to build an object file
Texture.cc.o:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Texture.cc.o
.PHONY : Texture.cc.o

Texture.i: Texture.cc.i

.PHONY : Texture.i

# target to preprocess a source file
Texture.cc.i:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Texture.cc.i
.PHONY : Texture.cc.i

Texture.s: Texture.cc.s

.PHONY : Texture.s

# target to generate assembly for a file
Texture.cc.s:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/Texture.cc.s
.PHONY : Texture.cc.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/spacepilot.dir/build.make CMakeFiles/spacepilot.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... spacepilot"
	@echo "... Bullet.o"
	@echo "... Bullet.i"
	@echo "... Bullet.s"
	@echo "... Enemy.o"
	@echo "... Enemy.i"
	@echo "... Enemy.s"
	@echo "... Entity.o"
	@echo "... Entity.i"
	@echo "... Entity.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... InputHandler.o"
	@echo "... InputHandler.i"
	@echo "... InputHandler.s"
	@echo "... Levels.o"
	@echo "... Levels.i"
	@echo "... Levels.s"
	@echo "... Menu.o"
	@echo "... Menu.i"
	@echo "... Menu.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Renderer.o"
	@echo "... Renderer.i"
	@echo "... Renderer.s"
	@echo "... Star.o"
	@echo "... Star.i"
	@echo "... Star.s"
	@echo "... Texture.o"
	@echo "... Texture.i"
	@echo "... Texture.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

